language: ruby

rvm:
 - '2.5.3'
 - '2.7.1'

env:
  global:
    - RAAR_DB_ADAPTER=postgresql
    - RAAR_DB_NAME=raar_test
    - RAAR_DB_USERNAME=postgres
    - AIRTIME_DB_ADAPTER=postgresql
    - AIRTIME_DB_NAME=airtime_test
    - AIRTIME_DB_USERNAME=postgres
    - PARALLEL_WORKERS=1

sudo: false

cache: bundler

services:
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg

before_script:
  - psql -c 'create database raar_test;' -U postgres
  - psql -c 'create database airtime_test;' -U postgres

script:
  - bundle exec rails test || cat log/test.log
  - bundle exec rubocop

before_deploy:
  - bundle exec rails package
