# Configure various aspects of the application.
#
# All setting keys that are accessed in the code must be defined
# in the default section.

default: &default
  archive_home: <%= ENV['ARCHIVE_HOME'] %>
  import_directories:
    <% ENV['IMPORT_DIRECTORIES'].to_s.strip.split(',').each do |d| %>
    - <%= d.strip %>
    <% end %>
  days_to_keep_imported: <%= ENV['DAYS_TO_KEEP_IMPORTED'] %>
  days_to_finish_import: <%= ENV['DAYS_TO_FINISH_IMPORT'] %>
  parallel_transcodings: <%= ENV['PARALLEL_TRANSCODINGS'] || 1 %>
  import_default_show_id: <%= ENV['IMPORT_DEFAULT_SHOW_ID'] %>
  ssl: <%= ENV['RAAR_SSL'] == 'true' %>
  host_name: <%= ENV['RAAR_HOST_NAME'] %>
  base_path: <%= ENV['RAAR_BASE_PATH'] %>
  admin_groups: <%= ENV['RAAR_ADMIN_GROUPS'] || 'admins,root' %>
  days_to_expire_api_key: <%= ENV['DAYS_TO_EXPIRE_API_KEY'] %>
  minutes_to_expire_jwt_token: <%= ENV['MINUTES_TO_EXPIRE_JWT_TOKEN'] || 60 %>

development:
  <<: *default
  archive_home: <%= Rails.root.join('tmp', 'development', 'archive') %>
  import_directories:
    <% dirs = ENV['IMPORT_DIRECTORIES'] || Rails.root.join('tmp', 'development', 'import')
       dirs.to_s.strip.split(',').each do |d| %>
    - <%= d.strip %>
    <% end %>
  days_to_keep_imported: <%= ENV['DAYS_TO_KEEP_IMPORTED'] || 1 %>
  days_to_finish_import: <%= ENV['DAYS_TO_FINISH_IMPORT'] || 1 %>
  parallel_transcodings: 4
  host_name: localhost:3000

test:
  <<: *default
  archive_home: <%= Rails.root.join('tmp', 'test', 'archive') %>
  import_directories:
    - <%= Rails.root.join('tmp', 'test', 'import') %>
  days_to_keep_imported: 1
  days_to_finish_import: 1
  parallel_transcodings: 4
  host_name: example.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
